@BASE=http://localhost:5003


POST {{BASE}}/auth/register
Content-Type: application/json

    {
        "firstName": "jhon",
        "lastName" : "doe",
        "email"    : "jdoe@example.com",
        "password" : "jdoe123"
    }