@BASE=http://localhost:5000


GET  {{BASE}}/zikkims
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YzFlZTA5Mi1lN2IxLTRmNDItOGYyNi1kZTZmYTYzOWU0NTQiLCJnaXZlbl9uYW1lIjoiamhvbiIsImZhbWlseV9uYW1lIjoiZG9lIiwianRpIjoiY2RjNjFlYTctZWMwMC00MzY3LWFlYWYtMDk5ZjQ3ZGIyYmM4IiwiZXhwIjoxNjk5ODQxNDQ4LCJpc3MiOiJaZWhpclppa2tpbSIsImF1ZCI6IlplaGlyWmlra2ltIn0.Fd0f8_UJNVlW7Ods3H1ERHmMyZKlTFJIeKpfZypNw08